from pathlib import Path
p=Path(__file__).parent
src=(p.parent/'editorial-hero/template.html').read_text()
src=src.replace('<body id="top">','<body id="top" data-view="home">\n<div id="hero-region">')
src=src.replace('    <div id="motion-stage" aria-hidden="true">','    <div id="motion-stage">')
src=src.replace('    </div>\n\n    <header', '    <div id="card-choices" aria-label="Choose a card from the deck"></div></div>\n\n    <header',1)
src=src.replace('A space for reflection','Tarot, thoughtfully personal')
src=src.replace('class="almanac-link" href="https://oliviaarcana.com/daily"','class="almanac-link" href="#journal"')
src=src.replace('The almanac</a>','My almanac</a>')
src=src.replace('href="https://oliviaarcana.com/oracle"','href="#question"')
src=src.replace('An ancient art. An open mind.','A personal practice of tarot')
src=src.replace('Pause. Draw a card.<br>Find a new perspective.','One card. A thoughtful interpretation.<br>A space to hear yourself more clearly.')
src=src.replace('<a class="reading-link" href="#question"><span>Begin a reading</span>', '<a class="reading-link" href="#question"><span>Draw your card</span>',1)
src=src.replace('</section>\n\n    <div class="deck-caption"','<p class="reading-facts">22 Major Arcana · No account needed</p><a id="resume-link" class="quiet-link" href="#journal" hidden>Return to your last reflection ↗</a></section>\n\n    <div class="deck-caption"',1)
src=src.replace('The olive lattice<br><em>A world waiting to unfold.</em>','The Olivia deck<br><em>Olive, ivory &amp; lapis.</em>')
src=src.replace('<span class="scroll-cue">','<a class="scroll-cue" href="#discover">').replace('<span id="scroll-label">Scroll to discover</span></span>','<span id="scroll-label">Discover the practice</span></a>')
src=src.replace('  </main>','''    <button id="leave-cinema" class="quiet-link" hidden>← Back to Olivia</button>
    <section id="question-view" class="ritual-copy" hidden aria-labelledby="question-title">
      <p class="eyebrow">A moment for you</p><h2 id="question-title" tabindex="-1">What is on<br><em>your mind?</em></h2>
      <p>You can bring a question, or simply arrive as you are.</p>
      <form id="question-form"><label for="question">Your question <span>(optional)</span></label><textarea id="question" rows="2" maxlength="500" placeholder="What would I like to see more clearly?"></textarea>
      <fieldset><legend>A place to begin</legend><div class="intention-options"><label><input type="radio" name="intention" value="open" checked><span>Stay open</span></label><label><input type="radio" name="intention" value="relationships"><span>Relationships</span></label><label><input type="radio" name="intention" value="work"><span>Work</span></label><label><input type="radio" name="intention" value="change"><span>Change</span></label></div></fieldset>
      <button class="solid-action" type="submit">Open the deck <span>↗</span></button><p class="privacy-note">Your question stays in this browser. The guide uses curated card meanings.</p></form>
      <button class="quiet-link" data-home>← Return to Olivia</button>
    </section>
    <section id="choose-view" hidden aria-labelledby="choose-title"><div class="choose-heading"><p class="eyebrow">Let your attention settle</p><h2 id="choose-title" tabindex="-1">One card.<br><em>Yours to discover.</em></h2><p>Choose a card that draws your eye.</p></div><div class="choose-footer"><button id="random-card" class="text-action">Choose one for me <span>↗</span></button><button class="quiet-link" id="change-question">← Your question</button><p id="choose-status" role="status"></p></div></section>
  </main></div>
  <div id="home-content">
    <section id="discover" class="editorial-section"><div class="section-index">01 / THE PRACTICE</div><div class="section-main"><h2>A small ritual.<br><em>A different perspective.</em></h2><p class="section-lede">Tarot gives a question a shape. A symbol to sit with. A thought you might not have found on your own.</p><div class="steps"><div><span>01</span><h3>Bring a question.</h3><p>Something specific, something unfinished, or nothing at all.</p></div><div><span>02</span><h3>Let a card speak.</h3><p>Draw from the Major Arcana. Explore its meaning and a question for reflection.</p></div><div><span>03</span><h3>Make it your own.</h3><p>Write what resonates. Keep the reading in your personal almanac.</p></div></div></div></section>
    <section class="sample-section" aria-labelledby="sample-title"><div class="sample-art"><img id="sample-art" alt="The Hermit, an ivory figure carrying a lantern against lapis blue" loading="lazy"><span>IX / THE HERMIT</span></div><div class="sample-copy"><p class="eyebrow">An example, before you begin</p><h2 id="sample-title">See what a<br><em>reading feels like.</em></h2><blockquote>“What deserves my attention while I consider a change?”</blockquote><p>The Hermit invites a little distance from the noise. Which part of this decision needs your own attention before another opinion?</p><a href="#sample" class="text-action">Explore this sample <span>↗</span></a><p class="privacy-note">A sample reading, not your personal draw.</p></div></section>
    <section class="editorial-section rooms-section"><div class="section-index">02 / YOUR ALMANAC</div><div class="section-main"><h2>A place to<br><em>return to yourself.</em></h2><p class="section-lede">Keep the moments that matter. Learn the language of the cards. Notice how your own perspective changes.</p><div class="room-links"><a href="#journal"><span>Keep</span><h3>Your reflections</h3><i>↗</i></a><a data-site="/academy" href="https://oliviaarcana.com/academy"><span>Learn</span><h3>The language of tarot</h3><i>↗</i></a><a data-site="/daily" href="https://oliviaarcana.com/daily"><span>Return</span><h3>The daily almanac</h3><i>↗</i></a></div></div></section>
    <footer class="product-footer"><a class="brand" href="#home">Olivia <span>ARCANA</span></a><p>A practice of attention.<br>Ancient symbols. Your own meaning.</p><a href="#question" class="text-action">Draw your card ↗</a></footer>
  </div>
  <main id="reading-view" class="product-page" hidden aria-labelledby="result-title"><div class="page-top"><a href="#home" class="brand">Olivia <span>ARCANA</span></a><a href="#journal" class="quiet-link">My almanac ↗</a></div><div class="reading-layout"><div class="reading-art"><div id="reveal-card"><img id="reading-image" alt=""></div><p id="card-index" class="eyebrow"></p></div><article class="reading-copy"><p class="eyebrow" id="reading-kind">Your one-card reading</p><p id="reading-question" class="question-quote"></p><h1 id="result-title" tabindex="-1"></h1><p id="meaning" class="meaning"></p><p id="intention-frame" class="intention-frame"></p><div class="reflection-prompt"><span class="eyebrow">A question to keep</span><p id="reflection-prompt"></p></div><p id="practice"></p><details class="card-lesson"><summary>Inside this card <span>+</span></summary><p id="card-lesson"></p><a data-site="/academy" href="https://oliviaarcana.com/academy">Explore the tarot library ↗</a></details><section id="save-section"><label for="reflection">What does this bring up for you? <span>(optional)</span></label><textarea id="reflection" rows="3" maxlength="4000" placeholder="A thought, a feeling, a small next step…"></textarea><div class="save-actions"><button id="save-reading" class="solid-action">Keep this reading <span>↗</span></button><a href="#journal" class="quiet-link" id="view-saved" hidden>Open my almanac</a></div><p id="save-status" role="status"></p><button id="download-reading" class="quiet-link">Download a copy ↓</button><p class="privacy-note">Saved only in this browser, on this device. Download a copy to keep a backup.</p></section><div id="sample-cta" hidden><a href="#question" class="solid-action">Draw your own card ↗</a></div><p class="provenance">A curated reflection on tarot symbolism. Your question is held alongside the card; this is not an AI-generated analysis of it.</p><a href="#question" class="quiet-link">Begin a new reading ↗</a><a data-site="/oracle?entry=hero" href="https://oliviaarcana.com/oracle?entry=hero" class="quiet-link advanced-link">Explore a full spread ↗</a></article></div></main>
  <main id="journal-view" class="product-page journal-page" hidden aria-labelledby="journal-title"><div class="page-top"><a href="#home" class="brand">Olivia <span>ARCANA</span></a><a href="#question" class="quiet-link">Draw a card ↗</a></div><div class="journal-intro"><p class="eyebrow">Your personal almanac</p><h1 id="journal-title" tabindex="-1">The things<br><em>you notice.</em></h1><p>Readings and reflections, kept together.<br>A record of your perspective as it changes.</p></div><p id="journal-status" role="status"></p><div id="journal-list"></div><div class="journal-bottom"><button id="export-journal" class="text-action">Download my almanac ↓</button><p class="privacy-note">Private to this browser and device. Clearing browser data removes these entries.</p></div></main>
  <div class="sr-only" id="product-status" role="status" aria-live="polite"></div>''',1)
src=src.replace('/*HERO*/</script>','window.OLIVIA_ASSETS={back:BACK_DATA,cards:DETAIL_DATA};\n/*HERO*/</script>')
src=src.replace('  <script>/*BACKGROUND*/</script>','  <script>/*BACKGROUND*/</script>\n  <script>/*APP*/</script>')
(p/'template.html').write_text(src)
# Keep all authored card/camera paths; bridge their drawn positions to keyboard-accessible choices.
h=(p/'hero.js').read_text()
h=h.replace('const diagnostics={};','const diagnostics={}; let hitTargets=[]; const cinematic=()=>document.body.classList.contains("cinema");')
h=h.replace('if(watching||freezeTime)scrollTo','if(cinematic()&&(watching||freezeTime))scrollTo').replace('else if(!freezeTime)target=', 'else if(cinematic()&&!freezeTime)target=')
h=h.replace('renderShadows(worldLayers);','''hitTargets=worldLayers.map(layer=>{const m=mul(camera.vp,layer.matrix);const points=[[-CARD_W/2,CARD_H/2],[CARD_W/2,CARD_H/2],[CARD_W/2,-CARD_H/2],[-CARD_W/2,-CARD_H/2]].map(([x,y])=>{const d=m[3]*x+m[7]*y+m[15];return [(m[0]*x+m[4]*y+m[12])/d*w/2+w/2,h/2-(m[1]*x+m[5]*y+m[13])/d*h/2];});return {index:layer.index,depth:layer.depth,points};});
 if(document.body.dataset.view==='choose')dispatchEvent(new CustomEvent('olivia:card-positions',{detail:hitTargets}));
 renderShadows(worldLayers);''')
h=h.replace("if(quiet||watching)return;const next", "if(!cinematic()||quiet||watching)return;const next")
h=h.replace("progressVelocity=0;scrollTo({top:p*scrollRange(),behavior:'instant'});draw();", "progressVelocity=0;if(cinematic())scrollTo({top:p*scrollRange(),behavior:'instant'});draw();")
h=h.replace('window.motionStudy={setProgress,','window.motionStudy={setProgress,stopJourney,resize:queueResize,targets:()=>hitTargets,')
(p/'hero.js').write_text(h)
b=(p/'build.py').read_text().replace("'outputs/olivia-editorial.html'","'outputs/olivia-almanac.html'")
b=b.replace('def data(f):', '''subprocess.run([str(dependencies/'.bin/esbuild'),str(p/'app.js'),'--bundle','--format=iife','--minify','--target=es2022','--outfile='+str(p/'app.bundle.js')],check=True)
def data(f):''')
b=b.replace("'/*BACKGROUND*/':", "'/*APP*/':(p/'app.bundle.js').read_text().replace('</script','<\\\\/script'),'/*BACKGROUND*/':")
(p/'build.py').write_text(b)
