/**
 * Card academy leaves: one written page per card, in English and Ukrainian,
 * grounded in the Olivia artwork. The JSON files in ./leaves are the source;
 * ./leaves/index.ts is generated by scripts/academy-leaves-index.mjs.
 */

import { LEAF_FILES } from "./leaves";

export type LeafLocale = "en" | "uk";

export interface LeafSymbolText {
  name: string;
  seen: string;
  meaning: string;
}

export interface LeafSymbol {
  key: string;
  /** Centre of the element, as percentages of the artwork's width and height. */
  x: number;
  y: number;
  en: LeafSymbolText;
  uk: LeafSymbolText;
}

export interface LeafText {
  essence: string;
  keywords: { upright: string[]; reversed: string[] };
  upright: string[];
  reversed: string[];
  number: string;
  tradition: string;
  court?: { temperament: string; gifts: string; shadow: string };
  areas: { love: string; work: string; self: string };
  positions: { heart: string; challenge: string; advice: string };
  pairs: { with: number; text: string }[];
  questions: string[];
  practice: string;
}

export interface Leaf {
  id: number;
  slug: string;
  artwork: { file: string; sha256: string };
  symbols: LeafSymbol[];
  en: LeafText;
  uk: LeafText;
}

const LEAVES: Leaf[] = (LEAF_FILES as unknown as Leaf[]).filter((leaf) => leaf.en && leaf.uk);
const BY_SLUG = new Map(LEAVES.map((leaf) => [leaf.slug, leaf]));
const BY_ID = new Map(LEAVES.map((leaf) => [leaf.id, leaf]));

export function leafBySlug(slug: string): Leaf | undefined {
  return BY_SLUG.get(slug);
}

export function leafById(id: number): Leaf | undefined {
  return BY_ID.get(id);
}

/** Cards that share the most symbol keys with this one, strongest first. */
export function cardsSharingSymbols(leaf: Leaf, limit = 4): { id: number; shared: string[] }[] {
  const own = new Set(leaf.symbols.map((s) => s.key).filter((k) => k !== "other"));
  return LEAVES.filter((other) => other.id !== leaf.id)
    .map((other) => ({ id: other.id, shared: [...new Set(other.symbols.map((s) => s.key))].filter((k) => own.has(k)) }))
    .filter((entry) => entry.shared.length > 0)
    .sort((a, b) => b.shared.length - a.shared.length || a.id - b.id)
    .slice(0, limit);
}
