/**
 * Which symbol keys have a trail in the reading experience's Symbol Trails
 * (#symbols/<trail>). Card pages link each described element to its trail.
 */

export const SYMBOL_TRAIL_OF: Record<string, string> = {
  "angel": "angels",
  "ankh": "throne",
  "arch": "thresholds",
  "bird": "birds",
  "blindfold": "veiled",
  "boat": "journey",
  "bridge": "journey",
  "butterfly": "birds",
  "candle": "flame",
  "castle": "towers",
  "cat": "lion",
  "cave": "mountain",
  "chalice": "cup",
  "cherub": "angels",
  "child": "child",
  "circle": "circle",
  "city": "towers",
  "cliff": "mountain",
  "cloak": "veiled",
  "cloud": "weather",
  "crayfish": "water",
  "crown": "crown",
  "cup": "cup",
  "curtain": "thresholds",
  "cypress": "harvest",
  "desert": "mountain",
  "dove": "birds",
  "eagle": "birds",
  "fish": "water",
  "flame": "flame",
  "flowers": "flowers",
  "fruit": "harvest",
  "garden": "harvest",
  "gate": "thresholds",
  "grapes": "harvest",
  "halo": "crown",
  "hand": "hand",
  "heart": "heart",
  "hood": "veiled",
  "horse": "horse",
  "house": "towers",
  "infinity": "circle",
  "island": "water",
  "lantern": "flame",
  "laurel": "crown",
  "leaves": "harvest",
  "lightning": "weather",
  "lily": "flowers",
  "lion": "lion",
  "mask": "veiled",
  "milky-way": "lapis-night",
  "moon": "moon",
  "mountain": "mountain",
  "orb": "throne",
  "owl": "birds",
  "path": "journey",
  "pentacle": "pentacle",
  "pillar": "thresholds",
  "pomegranate": "harvest",
  "pool": "water",
  "rain": "weather",
  "rainbow": "weather",
  "river": "water",
  "rock": "mountain",
  "rose": "flowers",
  "scales": "throne",
  "sceptre": "throne",
  "sea": "water",
  "serpent": "circle",
  "sphinx": "lion",
  "spiral": "circle",
  "staff": "wand",
  "star": "star",
  "stars-crown": "star",
  "sun": "sun",
  "sunflower": "sun",
  "swallow": "birds",
  "sword": "sword",
  "tears": "water",
  "throne": "throne",
  "torch": "flame",
  "tower": "towers",
  "tree": "harvest",
  "veil": "thresholds",
  "vine": "harvest",
  "wall": "thresholds",
  "wand": "wand",
  "water-pouring": "water",
  "waterfall": "water",
  "wheat": "harvest",
  "wheel": "circle",
  "window": "thresholds",
  "wings": "angels",
  "wreath": "crown"
};

/** `cardId` opens the trail at this card when the trail follows it; otherwise at its first card. */
export function symbolTrailFor(key: string, locale: "en" | "uk", cardId?: number): { id: string; href: string } | undefined {
  const id = SYMBOL_TRAIL_OF[key];
  if (!id) return undefined;
  return { id, href: `${locale === "uk" ? "/uk/" : "/"}#symbols/${id}${cardId === undefined ? "" : `/${cardId}`}` };
}
