from pathlib import Path
import subprocess
p=Path(__file__).resolve().parent
root=p.parent.parent
subprocess.run([str(p/'node_modules/.bin/esbuild'),str(p/'background.js'),'--bundle','--format=iife','--minify','--target=es2022','--legal-comments=inline','--outfile='+str(p/'background.bundle.js')],check=True)
html=(root/'outputs/olivia-hero-v12-preview.html').read_text()
html=html.replace('<title>Olivia Arcana — A world within</title>','<title>Olivia Arcana — Three atmospheres</title>')
html=html.replace('</style><noscript>','\n'+(p/'study.css').read_text()+'\n</style><noscript>',1)
html=html.replace('<canvas aria-hidden="true"></canvas>','<canvas id="cards" aria-hidden="true"></canvas><canvas id="atmosphere" aria-hidden="true" data-state="loading"></canvas>',1)
html=html.replace("canvas=$('canvas')","canvas=$('#cards')",1)
# Comparison controls select still compositions even with reduced motion.
html=html.replace('const progress=quiet?1:p,camera=cameraPose(progress);','const progress=p,camera=cameraPose(progress);',1)
# A still composition must occupy its actual position in the scroll spine.
# Release it on real scrolling, including keyboard/scrollbar/touch input, but
# ignore the scroll event generated by selecting that same composition.
old_scroll='function onScroll(){if(freezeTime||watching)return;target=clamp(scrollY/scrollRange());wake();}'
new_scroll='function onScroll(){if(quiet||watching)return;const next=clamp(scrollY/scrollRange());if(freezeTime&&Math.abs(next-p)<.0002)return;freezeTime=false;target=next;wake();}'
old_pose='function setProgress(v){watching=false;freezeTime=true;target=p=clamp(v);progressVelocity=0;draw();}'
new_pose="function setProgress(v){watching=false;freezeTime=true;target=p=clamp(v);progressVelocity=0;scrollTo({top:p*scrollRange(),behavior:'instant'});draw();}"
assert old_scroll in html and old_pose in html, 'V12 motion hooks changed; review comparison handoff.'
html=html.replace(old_scroll,new_scroll,1).replace(old_pose,new_pose,1)
html=html.replace("if(watching)scrollTo({top:target*scrollRange(),behavior:'instant'});else if(!freezeTime)","if(watching||freezeTime)scrollTo({top:target*scrollRange(),behavior:'instant'});else if(!freezeTime)",1)
controls='''<aside class="study-controls" aria-label="Compare background atmospheres">
<div class="study-intro"><p class="study-heading">Olivia Arcana · Three atmospheres</p><p class="study-note" id="atmosphere-note"></p></div>
<div class="palettes" role="group" aria-label="Background palette">
<button type="button" data-palette-choice="charcoal" aria-pressed="true"><i style="--swatch:#45464c" aria-hidden="true"></i>01 Charcoal</button>
<button type="button" data-palette-choice="plum" aria-pressed="false"><i style="--swatch:#705963" aria-hidden="true"></i>02 Plum</button>
<button type="button" data-palette-choice="mineral" aria-pressed="false"><i style="--swatch:#cabcaa" aria-hidden="true"></i>03 Mineral</button>
</div><div class="study-tools"><div class="frames" role="group" aria-label="Card composition"><button type="button" data-frame="0" aria-pressed="false">Opening</button><button type="button" data-frame="0.82" aria-pressed="true">Moon reveal</button></div><button type="button" id="background-toggle" aria-pressed="false">Background only</button></div></aside><p id="render-note" role="status"></p>'''
bundle=(p/'background.bundle.js').read_text().replace('</script','<\\/script')
html=html.replace('</body>',controls+'<script>'+bundle+'</script></body>')
out=root/'outputs/olivia-backgrounds.html'
out.write_text(html)
print(out, out.stat().st_size)
