import {SPREADS,buildSpreadReading} from './spread-content.js';
import {createSpreadSession,selectSpreadCard,revealNext,revealAll,createSpreadRecord,loadSpreadRecords,saveSpreadRecord,removeSpreadRecord,exportSpreadRecords} from './spread-core.js';

/** The spread ritual is independent of the approved WebGL hero timeline. */
export function initSpreads({assets,names,show,goto,reduced,announce}) {
 const $=s=>document.querySelector(s), el=(tag,cls,txt)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(txt!==undefined)n.textContent=txt;return n;};
 const isSite=new URLSearchParams(location.search).get('site')==='1'&&parent!==window;
 const memberURL=isSite?'/pricing':'https://oliviaarcana.com/pricing';
 let access={status:isSite?'loading':'unavailable',paid:false},requestId='',accessTimer;
 let current=null,definition=null,session=null,reading=null,record=null,isPreview=false,active=-1,playing=false,busy=false,generation=0,flowGeneration=0,unsaved=false;
 const animations=new Set(), drafts=new Map(),dirty=new Set();
 const previewQuestion='What would help me approach an important change with more clarity?';
 const previewIds={clarity3:[9,18,14],crossroads5:[6,7,12,2,14],compass8:[18,9,2,16,15,8,12,17]};
 const root=el('main','product-page spread-page');root.id='spreads-view';root.hidden=true;root.setAttribute('aria-labelledby','spreads-title');
 root.innerHTML=`<div class="page-top"><a class="brand" href="#home">Olivia <span>ARCANA</span></a><a class="quiet-link" href="#journal">My almanac ↗</a></div>
 <div id="spread-library"><div class="spread-intro"><div><p class="eyebrow">A fuller conversation · For members</p><h1 id="spreads-title" tabindex="-1">When a question<br>has <em>many sides.</em></h1></div><p>Let each card hold a different part of the picture. Explore what connects them, then find a step that feels like your own.</p></div><div class="spread-options" id="spread-options"></div>
 <div class="spread-entry"><div><p class="eyebrow">Your question, held in context</p><h2>Choose the space<br><em>you need.</em></h2><p>A small spread can be enough. Choose more cards when there are genuinely different parts of a situation to explore.</p><p class="privacy-note">Drawn from Olivia’s 22 Major Arcana. All cards are read upright. Interpretations are curated reflections, not predictions.</p></div><form id="spread-question-form"><label for="spread-question">Your question <span>(optional · up to 240 characters)</span></label><textarea id="spread-question" maxlength="240" rows="3" placeholder="What do I need to understand about this situation?"></textarea><div id="spread-paths" hidden><label for="spread-path-a">Path A<input id="spread-path-a" maxlength="120" placeholder="Your first option"></label><label for="spread-path-b">Path B<input id="spread-path-b" maxlength="120" placeholder="Your second option"></label></div><fieldset><legend>A place to begin</legend><div class="intention-options"><label><input type="radio" name="spread-intention" value="open" checked><span>Stay open</span></label><label><input type="radio" name="spread-intention" value="relationships"><span>Relationships</span></label><label><input type="radio" name="spread-intention" value="work"><span>Work</span></label><label><input type="radio" name="spread-intention" value="change"><span>Change</span></label></div></fieldset><p id="spread-access" role="status"></p><button class="solid-action" id="begin-spread" type="submit">Begin this spread ↗</button><a id="spread-membership" class="text-action">Explore membership ↗</a><button type="button" id="refresh-spread-access" class="quiet-link">Check my membership again</button><p class="privacy-note">One-card readings are free. Guided spreads are for members. Your question and reflections stay in this browser.</p><a href="#question" class="quiet-link">Prefer a single card? Begin here ↗</a></form></div></div>
 <section id="spread-ritual" hidden aria-labelledby="spread-ritual-title"><div class="spread-ritual-head"><div><p class="eyebrow" id="spread-kind"></p><h1 id="spread-ritual-title" tabindex="-1"></h1><p id="spread-held-question" class="question-quote"></p></div><button class="quiet-link" id="leave-spread">← All spreads</button></div><div class="spread-workspace"><div class="spread-scene"><div id="spread-board" class="spread-board" aria-label="Your spread"></div><div id="spread-deck-area"><p class="eyebrow" id="spread-pick-label"></p><div class="spread-deck" id="spread-deck" aria-label="Choose cards from the deck"></div><button class="text-action" id="deal-spread">Let the deck choose ↗</button></div><div class="spread-controls"><a href="#spread-position-copy" id="explore-position" class="quiet-link" hidden>Explore this card ↓</a><p id="spread-progress" role="status"></p><div><button class="solid-action" id="reveal-next" hidden>Reveal the first card ↗</button><button class="quiet-link" id="reveal-flow" hidden>Watch the reveal</button><button class="quiet-link" id="reveal-skip" hidden>Reveal all now</button></div></div></div><aside class="spread-insight" aria-live="polite"><div id="spread-position-copy"></div><button id="show-synthesis" class="text-action" hidden>Read the cards together ↗</button></aside></div>
 <section class="spread-synthesis" id="spread-synthesis" hidden><div class="spread-synthesis-title"><p class="eyebrow">The whole picture</p><h2 tabindex="-1" id="spread-together-title">Read <em>together.</em></h2><p id="spread-synthesis-question" class="question-quote"></p></div><div class="spread-synthesis-copy"><div id="spread-paragraphs"></div><div class="reflection-prompt"><span class="eyebrow">A question to take with you</span><p id="spread-takeaway"></p></div><div id="spread-save-section"><label for="spread-reflection">What connects with your life? <span>(optional)</span></label><textarea id="spread-reflection" maxlength="4000" rows="3" placeholder="The connection I notice. The next step I can take…"></textarea><div class="save-actions"><button id="save-spread" class="solid-action">Keep this spread ↗</button><a href="#journal" class="quiet-link">My almanac ↗</a></div><p id="spread-save-status" role="status"></p><button id="download-spread" class="quiet-link">Download this spread ↓</button><p class="privacy-note">Saved on this browser and device. Download a copy for your own backup.</p></div><div id="spread-preview-cta" hidden><p>This is a fixed example, so you can explore the experience.</p><a class="text-action" id="preview-membership">Make room for your own question ↗</a></div><p class="provenance">Curated card meanings, interpreted through each position and read in relation to one another. Your question is shown alongside them; this guide does not analyse your words or know another person’s thoughts.</p><button class="quiet-link" id="another-spread">Choose another spread ↗</button></div></section></section>`;
 $('#journal-view').before(root);
 for(const id of ['#spread-membership','#preview-membership']){$(id).href=memberURL;if(isSite)$(id).target='_top';}
 const selected=()=>SPREADS.find(s=>s.id===current)||SPREADS[0];
 function optionDiagram(s){const diagram=el('div','spread-diagram');diagram.setAttribute('aria-hidden','true');for(const [i,p] of s.layout.entries()){const c=el('span','diagram-card',String(i+1));c.style.cssText=`left:${p.x*100}%;top:${p.y*100}%;transform:translate(-50%,-50%) rotate(${p.rotate||0}deg)`;diagram.append(c);}return diagram;}
 for(const s of SPREADS){const article=el('article','spread-option');article.dataset.spread=s.id;const b=el('button','spread-option-select');b.type='button';b.setAttribute('aria-pressed','false');b.append(optionDiagram(s),el('span','eyebrow',`${s.count} cards · ${s.kicker}`),el('h2','',s.name),el('p','',s.description));b.addEventListener('click',()=>chooseDefinition(s.id));const ol=el('ol','spread-position-list');s.positions.forEach(p=>ol.append(el('li','',p.label)));const preview=el('button','quiet-link',`Preview ${s.name} ↗`);preview.type='button';preview.addEventListener('click',()=>start(s,true));article.append(b,ol,preview);$('#spread-options').append(article);}
 function chooseDefinition(id){current=id;$('#spread-paths').hidden=id!=='crossroads5';for(const input of $('#spread-paths').querySelectorAll('input'))input.required=id==='crossroads5';for(const a of document.querySelectorAll('.spread-option')){const checked=a.dataset.spread===id;a.classList.toggle('selected',checked);a.querySelector('button').setAttribute('aria-pressed',String(checked));}$('#begin-spread').textContent=`Begin ${selected().name} ↗`;}
 chooseDefinition(SPREADS[0].id);
 function refreshAccess(){clearTimeout(accessTimer);if(!isSite){access={status:'unavailable',paid:false};renderAccess();return;}access={status:'loading',paid:false};renderAccess();requestId=crypto.randomUUID();parent.postMessage({type:'olivia:subscription:request',requestId},location.origin);accessTimer=setTimeout(()=>{if(access.status==='loading'){access={status:'unavailable',paid:false};renderAccess();}},10000);}
 function renderAccess(){const paid=access.status==='ready'&&access.paid===true;$('#begin-spread').hidden=!paid;$('#spread-membership').hidden=paid||access.status==='loading';$('#refresh-spread-access').hidden=!isSite||access.status==='loading';$('#spread-access').textContent=access.status==='loading'?'Checking your membership…':paid?'Your membership includes all three guided spreads.':access.status==='unavailable'?'Membership cannot be verified here. You can explore every spread with a free preview.':'Guided spreads are included with a paid membership. Explore a free preview above.';}
 addEventListener('message',event=>{const data=event.data;if(!isSite||event.source!==parent||event.origin!==location.origin||data?.type!=='olivia:subscription:state'||data.requestId!==requestId||!['loading','ready','unavailable'].includes(data.status))return;access={status:data.status,paid:data.paid===true&&['insight','premium','vip'].includes(data.tier)};if(data.status!=='loading')clearTimeout(accessTimer);renderAccess();});
 $('#refresh-spread-access').addEventListener('click',refreshAccess);refreshAccess();
 $('#explore-position').addEventListener('click',e=>{e.preventDefault();$('#spread-position-copy').scrollIntoView({behavior:reduced()?'instant':'smooth',block:'start'});$('#spread-position-copy').tabIndex=-1;$('#spread-position-copy').focus({preventScroll:true});});
 const status=message=>{$('#spread-progress').textContent=message;announce(message);};
 function preserve(){if(record&&!isPreview){record={...record,note:$('#spread-reflection').value};drafts.set(record.id,record);}}
 function halt(){generation++;flowGeneration++;playing=false;busy=false;for(const animation of animations)animation.cancel();animations.clear();$('#reveal-flow').textContent='Watch the reveal';}
 function leave(){preserve();halt();root.hidden=true;}
 function enter(){show('spreads');root.hidden=false;}
 function library(){preserve();halt();enter();root.setAttribute('aria-labelledby','spreads-title');$('#spread-library').hidden=false;$('#spread-ritual').hidden=true;$('#spreads-title').focus({preventScroll:true});renderAccess();}
 function runAnimation(node,frames,options){if(reduced())return Promise.resolve();const animation=node.animate(frames,options);animations.add(animation);if(document.hidden)animation.pause();return animation.finished.catch(()=>{}).finally(()=>animations.delete(animation));}
 document.addEventListener('visibilitychange',()=>{for(const animation of animations)document.hidden?animation.pause():animation.play();});
 matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(reduced())for(const animation of animations)animation.finish();});
 function initBoard(){const board=$('#spread-board');board.replaceChildren();board.dataset.count=definition.count;for(const [i,p] of definition.positions.entries()){const pos=definition.layout[i];const slot=el('div','spread-slot');slot.dataset.index=i;slot.style.cssText=`--x:${pos.x*100}%;--y:${pos.y*100}%;--angle:${pos.rotate||0}deg`;const b=el('button','spread-card');b.type='button';b.disabled=true;b.setAttribute('aria-label',`${i+1}. ${p.label}. Waiting for a card.`);const rotator=el('span','spread-card-turn');const back=el('img','spread-card-back');back.src=assets.back;back.alt='';const face=el('img','spread-card-face');face.alt='';rotator.append(back,face);b.append(rotator);const label=el('span','spread-slot-label',`${String(i+1).padStart(2,'0')} · ${p.label}`);slot.append(b,label);b.addEventListener('click',()=>{if(i<session.revealedCount)inspect(i);else if(i===session.revealedCount&&session.cardIds.length===definition.count)revealOne();});board.append(slot);} }
 function buildDeck(){const deck=$('#spread-deck');deck.replaceChildren();for(let slot=0;slot<22;slot++){const b=el('button','spread-deck-card');b.type='button';b.dataset.slot=slot;b.setAttribute('aria-label',`Choose card ${slot+1} for the spread`);const image=el('img');image.src=assets.back;image.alt='';b.style.setProperty('--slot',slot);b.append(image);b.addEventListener('click',()=>{if(!busy&&!playing)dealOne(slot);});deck.append(b);} }
 function prepareView(){enter();root.setAttribute('aria-labelledby','spread-ritual-title');$('#spread-library').hidden=true;$('#spread-ritual').hidden=false;$('#spread-synthesis').hidden=true;$('#spread-kind').textContent=isPreview?'A sample spread · 22 Major Arcana':`${definition.count} cards · Your guided reading`;$('#spread-ritual-title').textContent=definition.name;$('#spread-held-question').textContent=session.question?`“${session.question}”`:'An open reading';$('#spread-together-title').textContent='Read together.';$('#spread-reflection').value=record?.note||'';$('#spread-save-status').textContent='';$('#spread-save-section').hidden=isPreview;$('#spread-preview-cta').hidden=!isPreview;$('#spread-ritual-title').focus({preventScroll:true});initBoard();buildDeck();controls();initialCopy();}
 function start(s,preview){if(!preview&&!(access.status==='ready'&&access.paid)){renderAccess();return;}preserve();halt();definition=s;chooseDefinition(s.id);isPreview=preview;record=null;active=-1;const intention=new FormData($('#spread-question-form')).get('spread-intention');session=createSpreadSession({question:preview?(s.id==='crossroads5'?previewQuestion+'\nPath A: make the change. Path B: stay and reshape the current situation.':previewQuestion):s.id==='crossroads5'?[$('#spread-question').value,'Path A: '+$('#spread-path-a').value,'Path B: '+$('#spread-path-b').value].filter(Boolean).join('\n'):$('#spread-question').value,intention:preview?'change':intention,spreadId:s.id,count:s.count});if(preview){const order=[...previewIds[s.id],...Array.from({length:22},(_,i)=>i).filter(i=>!previewIds[s.id].includes(i))];session=Object.freeze({...session,deck:Object.freeze(order)});}reading=null;history.replaceState(null,'','#spreads');prepareView();status(preview?'A fixed example. Watch how each position adds to the picture.':`Choose ${s.count} cards, one at a time, or let the deck choose.`);if(preview)dealSequence();}
 $('#spread-question-form').addEventListener('submit',e=>{e.preventDefault();try{start(selected(),false);}catch{$('#spread-access').textContent='The deck could not be opened. Please try again.';}});
 function initialCopy(){const container=$('#spread-position-copy');container.replaceChildren(el('p','eyebrow','Every position has a purpose'),el('h2','', 'A place for each part.'),el('p','',definition.goodFor));const list=el('ol','spread-role-list');for(const p of definition.positions){const li=el('li');li.append(el('strong','',p.label),el('span','',p.prompt));list.append(li);}container.append(list);}
 function controls(){if(!session)return;const full=session.cardIds.length===definition.count,ready=full&&!!reading,complete=session.revealedCount===definition.count;$('#spread-deck-area').hidden=full;$('#reveal-next').hidden=!ready||complete;$('#reveal-next').disabled=busy||playing;$('#reveal-next').textContent=session.revealedCount?`Reveal ${definition.positions[session.revealedCount]?.label||'next card'} ↗`:'Reveal the first card ↗';$('#reveal-flow').hidden=!ready||complete;$('#reveal-flow').disabled=busy&&!playing;$('#reveal-skip').hidden=!ready||complete;$('#show-synthesis').hidden=!complete||busy;$('#explore-position').hidden=session.revealedCount===0||busy;$('#deal-spread').disabled=busy||playing;$('#spread-pick-label').textContent=full?'':`${session.cardIds.length} of ${definition.count} chosen · ${definition.positions[session.cardIds.length].label}`;for(const b of $('#spread-deck').children){b.disabled=busy||playing||session.selectedSlots.includes(Number(b.dataset.slot));b.classList.toggle('chosen',session.selectedSlots.includes(Number(b.dataset.slot)));}for(const [i,slot] of [...$('#spread-board').children].entries()){slot.querySelector('button').disabled=!ready||busy||playing||(!full&&i>=session.revealedCount)||i>session.revealedCount;} }
 async function dealOne(slot){if(session.cardIds.length>=definition.count)return;const token=generation;busy=true;const index=session.cardIds.length,source=$(`#spread-deck [data-slot="${slot}"]`),from=source.getBoundingClientRect();session=selectSpreadCard(session,slot);const target=$('#spread-board').children[index],card=target.querySelector('.spread-card');target.classList.add('dealt');card.setAttribute('aria-label',`${index+1}. ${definition.positions[index].label}. Reveal card.`);card.querySelector('.spread-card-face').src=assets.cards[session.cardIds[index]];const to=card.getBoundingClientRect();controls();status(`${index+1} of ${definition.count} · ${definition.positions[index].label}`);await runAnimation(card,[{transform:`translate(${from.x+from.width/2-to.x-to.width/2}px,${from.y+from.height/2-to.y-to.height/2}px) scale(.6) rotate(-14deg)`,opacity:0},{transform:`translate(${(from.x-to.x)*.38}px,${(from.y-to.y)*.36-50}px) scale(1.07) rotate(5deg)`,opacity:1,offset:.5},{transform:'translate(0,0) scale(1) rotate(0deg)',opacity:1}],{duration:1400,easing:'cubic-bezier(.22,.65,.2,1)'});if(token!==generation)return;busy=false;controls();if(session.cardIds.length===definition.count){reading=buildSpreadReading(definition,session.cardIds,session.intention);controls();status('Your spread is placed. Reveal at your own pace.');}}
 async function dealSequence(){if(busy||playing)return;playing=true;const token=generation;while(session.cardIds.length<definition.count&&token===generation){const slot=session.deck.findIndex((_,i)=>!session.selectedSlots.includes(i));await dealOne(slot);}if(token!==generation)return;playing=false;controls();}
 $('#deal-spread').addEventListener('click',dealSequence);
 function inspect(index){if(index>=session.revealedCount)return;active=index;for(const [i,slot] of [...$('#spread-board').children].entries()){slot.classList.toggle('active',i===index);slot.querySelector('button').setAttribute('aria-pressed',String(i===index));}const c=reading.cards[index],p=definition.positions[index],box=$('#spread-position-copy');box.replaceChildren(el('p','eyebrow',`${String(index+1).padStart(2,'0')} / ${p.label}`),el('h2','',names[c.cardId]),el('p','position-lens',p.prompt),el('p','',c.meaning));const prompt=el('div','reflection-prompt');prompt.append(el('span','eyebrow','Consider this'),el('p','',c.prompt));box.append(prompt,el('p','spread-practice',c.practice));}
 function renderRevealed(index){const slot=$('#spread-board').children[index],b=slot.querySelector('button');slot.classList.add('revealed');b.setAttribute('aria-label',`${index+1}. ${definition.positions[index].label}: ${names[session.cardIds[index]]}. Explore this card.`);b.querySelector('.spread-card-face').alt=names[session.cardIds[index]];}
 async function revealOne(){if(busy||session.revealedCount>=definition.count)return;const token=generation,index=session.revealedCount;busy=true;session=revealNext(session);renderRevealed(index);controls();const turn=$('#spread-board').children[index].querySelector('.spread-card-turn');await runAnimation(turn,[{transform:'rotateY(0deg)'},{transform:'rotateY(180deg)'}],{duration:1200,easing:'cubic-bezier(.4,0,.16,1)'});if(token!==generation)return;busy=false;inspect(index);status(`${index+1} of ${definition.count} revealed · ${definition.positions[index].label}: ${names[session.cardIds[index]]}`);if(session.revealedCount===definition.count)complete();controls();}
 async function flow(){if(playing){playing=false;flowGeneration++;$('#reveal-flow').textContent='Continue the reveal';controls();return;}if(busy)return;playing=true;const playback=++flowGeneration;$('#reveal-flow').textContent='Pause the reveal';const token=generation;while(playing&&session.revealedCount<definition.count&&token===generation&&playback===flowGeneration){await revealOne();if(token!==generation||playback!==flowGeneration)return;if(playing&&session.revealedCount<definition.count)await runAnimation($('#spread-progress'),[{opacity:1},{opacity:1}],{duration:1600});if(token!==generation||playback!==flowGeneration)return;}if(token!==generation||playback!==flowGeneration)return;playing=false;$('#reveal-flow').textContent='Watch the reveal';controls();}
 $('#reveal-next').addEventListener('click',revealOne);$('#reveal-flow').addEventListener('click',flow);
 $('#reveal-skip').addEventListener('click',()=>{halt();session=revealAll(session);session.cardIds.forEach((_,i)=>renderRevealed(i));inspect(session.revealedCount-1);complete();controls();status('All cards revealed. Explore each position or read them together.');});
 function complete(){if(!record&&!isPreview){record=createSpreadRecord(session,definition,reading);drafts.set(record.id,record);}const box=$('#spread-paragraphs');box.replaceChildren(...reading.synthesis.paragraphs.map(p=>el('p','',p)));$('#spread-takeaway').textContent=reading.synthesis.prompt;$('#spread-synthesis-question').textContent=session.question?`“${session.question}”`:'An open reading';$('#spread-synthesis').hidden=false;}
 $('#show-synthesis').addEventListener('click',()=>{$('#spread-synthesis').scrollIntoView({behavior:reduced()?'instant':'smooth',block:'start'});$('#spread-together-title').focus({preventScroll:true});});
 $('#spread-reflection').addEventListener('input',()=>{if(record&&!isPreview){dirty.add(record.id);unsaved=true;$('#spread-save-status').textContent='Unsaved reflection.';}});
 const notifyJournal=()=>dispatchEvent(new Event('olivia:journal-change'));
 $('#save-spread').addEventListener('click',()=>{if(!record||isPreview)return;preserve();try{record={...record,updatedAt:new Date().toISOString()};saveSpreadRecord(localStorage,record);drafts.set(record.id,record);dirty.delete(record.id);unsaved=dirty.size>0;$('#spread-save-status').textContent='Kept in your almanac, on this device.';notifyJournal();}catch(error){$('#spread-save-status').textContent=error.message||'This spread could not be saved. Download a copy to keep it.';}});
 function download(filename,content){const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=el('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 $('#download-spread').addEventListener('click',()=>{if(!record||isPreview)return;preserve();download('olivia-spread.json',exportSpreadRecords([record]));});
 for(const id of ['#leave-spread','#another-spread'])$(id).addEventListener('click',library);
 function restore(saved){preserve();halt();definition=SPREADS.find(s=>s.id===saved.spreadId);if(!definition)return;record=drafts.get(saved.id)||saved;isPreview=false;session={...record,count:record.cardIds.length,selectedSlots:[],deck:[]};reading={cards:record.cards,synthesis:record.synthesis};history.replaceState(null,'','#spreads');prepareView();session.cardIds.forEach((id,i)=>{const slot=$('#spread-board').children[i];slot.classList.add('dealt');slot.querySelector('.spread-card-face').src=assets.cards[id];renderRevealed(i);});complete();inspect(0);controls();status('Your saved spread. The original cards and positions are unchanged.');if(dirty.has(record.id))$('#spread-save-status').textContent='Unsaved reflection.';}
 function renderJournal(){const journal=$('#journal-list');$('#spread-journal-section')?.remove();const section=el('section','spread-journal-section');section.id='spread-journal-section';section.append(el('p','eyebrow','Your guided spreads'));const msg=el('p','spread-journal-message');section.append(msg);let records;try{records=loadSpreadRecords(localStorage);}catch(error){msg.textContent=error.message;journal.after(section);return;}const savedIds=new Set(records.map(r=>r.id)),merged=new Map(records.map(r=>[r.id,r]));for(const [id,draft]of drafts)if(!merged.has(id)||dirty.has(id))merged.set(id,draft);records=[...merged.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));if(journal.querySelector('.empty-journal'))journal.querySelector('.empty-journal').hidden=records.length>0;$('#export-journal').disabled=!records.length&&!journal.querySelector('.journal-entry');if(!records.length){section.append(el('p','spread-empty','A fuller reading can have a place here, too.'));const link=el('a','text-action','Explore guided spreads ↗');link.href='#spreads';section.append(link);}for(const r of records){const row=el('div','journal-entry'),button=el('button','journal-row');button.type='button';const image=el('img');image.src=assets.cards[r.cardIds[0]];image.alt='';const info=el('div');info.append(el('time','',new Date(r.createdAt).toLocaleDateString(undefined,{day:'numeric',month:'long',year:'numeric'})+(!savedIds.has(r.id)?' · Unsaved draft':dirty.has(r.id)?' · Unsaved changes':'')),el('h2','',`${r.spreadName} · ${r.cardIds.length} cards`),el('p','',r.question||r.note||'An open reading'));button.append(image,info,el('span','','↗'));button.addEventListener('click',()=>restore(r));row.append(button);const remove=el('button','quiet-link remove-entry','Remove');remove.type='button';remove.setAttribute('aria-label',`Remove ${r.spreadName} spread`);remove.addEventListener('click',()=>{try{removeSpreadRecord(localStorage,r.id);if(record?.id===r.id){record=null;session=null;reading=null;active=-1;}drafts.delete(r.id);dirty.delete(r.id);unsaved=dirty.size>0;notifyJournal();renderJournal();const message=$('#spread-journal-section .spread-journal-message');message.textContent='Spread removed. ';const undo=el('button','quiet-link','Undo');undo.addEventListener('click',()=>{try{saveSpreadRecord(localStorage,r);notifyJournal();renderJournal();}catch(error){message.textContent=error.message;}});message.append(undo);}catch(error){msg.textContent=error.message;}});row.append(remove);section.append(row);}if(records.length){const exp=el('button','text-action','Download my spreads ↓');exp.addEventListener('click',()=>download('olivia-spreads.json',exportSpreadRecords(records)));section.append(exp);}journal.after(section);}
 addEventListener('storage',()=>{for(const id of drafts.keys())if(!dirty.has(id))drafts.delete(id);if(document.body.dataset.view==='journal')renderJournal();});
 addEventListener('beforeunload',e=>{if(unsaved){e.preventDefault();e.returnValue='';}});
 return {leave,library,renderJournal,exportJournal(){const all=new Map(loadSpreadRecords(localStorage).map(r=>[r.id,r]));for(const [id,r]of drafts)if(!all.has(id)||dirty.has(id))all.set(id,r);return JSON.parse(exportSpreadRecords([...all.values()]));},open(){library();},restore};
}
