// Generated by scripts/academy-leaves-index.mjs. Do not edit by hand.
import file_crossroads_role_or_study from "./crossroads-role-or-study.json";
import file_inner_compass_restless_at_work from "./inner-compass-restless-at-work.json";

export const WORKED_READING_FILES = [file_crossroads_role_or_study, file_inner_compass_restless_at_work];
